name: Release

on:
  push:
    tags:
    - 'v*'

jobs:
  test:
    uses: clambin/workflows/.github/workflows/test.yaml@main
    secrets:
      codecov-token: ${{ secrets.CODECOV_TOKEN }}
  release:
    needs:
      - test
    uses: clambin/workflows/.github/workflows/release.yaml@docker
