name: Test
on:
  push:
  pull_request:
permissions:
  contents: read
jobs:
  test:
    uses: clambin/workflows/.github/workflows/test.yaml@main
    secrets:
      codecov-token: ${{ secrets.CODECOV_TOKEN }}

